### ISSUE TITLE
[CTD] Crash to desktop when picking Spawner with ChestTransporter

### ISSUE THREAD

**Issue by drakray** [cubex2/chesttransporter#37]
See https://github.com/ldtteam/minecolonies/issues/4718

Happen when on server
Crash with 
```
java.lang.NullPointerException: Unexpected error
	at com.minecolonies.coremod.colony.ColonyManager.getColonyByDimension(ColonyManager.java:269)
	at com.minecolonies.coremod.event.EventHandler.onBlockBreak(EventHandler.java:382)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1465_EventHandler_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at cubex2.mods.chesttransporter.ItemChestTransporter.onItemUseFirst(ItemChestTransporter.java:80)
	at net.minecraft.item.ItemStack.onItemUseFirst(ItemStack.java:200)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:409)
```

**Comment by Jwguy** [comment]
Seconding this. I've experienced this with players on my server as well.

**Comment by ExDomino** [comment]
This bug occur when MineColonies is installed, I'm wondering why.
Related to: https://github.com/ldtteam/minecolonies/issues/4718
